### ISSUE TITLE
Systemd user session support

### ISSUE THREAD

**Issue by Conan-Kudo** [Miriway/Miriway#123]
Miriway should support being invoked to run a systemd user session so that the compositor and shell components are correctly tracked and managed in a way that allow things like systemd-oomd to be aware and not kill it under memory pressure. It also would improve the reliability of process invocation and tracking like it did for MiracleWM.

An example of how this was done for MiracleWM is here: https://github.com/miracle-wm-org/miracle-wm/pull/228

**Comment by AlanGriffiths** [comment]
There's a start at copying Miracle here: #118

**Comment by AlanGriffiths** [comment]
Fixed by: #118
