### ISSUE TITLE
RFE: Add command-line option to point miriway to a config file location

### ISSUE THREAD

**Issue by Conan-Kudo** [Miriway/Miriway#129]
I'm working on adding support for Miriway to LXQt's Wayland session code, and one thing it wants is the ability to launch a compositor pointed to a configuration file nested in `~/.config/lxqt` rather than elsewhere so that all the LXQt configuration is underneath the common directory.

I can't seem to identify a way to tell miriway to launch looking at something like `~/.config/lxqt/miriway-shell.config`. It would be great to have an option added so I can wire up miriway into LXQt officially.

**Comment by AlanGriffiths** [comment]
This is similar to the approach described here: https://github.com/Miriway/Miriway/issues/122#issuecomment-2422532497

**Comment by AlanGriffiths** [comment]
...and there is a problem with both approaches: Mir upstream doesn't handle: [Mir doesn't handle watching config paths](https://github.com/canonical/mir/issues/3645) correctly.

With Mir's current behaviour, we could implement something like `~/.config/lxqt-miriway-shell.config`, but I think fixing Mir first is a better plan.

**Comment by AlanGriffiths** [comment]
> ...and there is a problem with both approaches: Mir upstream doesn't handle: [Mir doesn't handle watching config paths](https://github.com/canonical/mir/issues/3645) correctly.

Actually, that's a thinko - the configuration we're talking about isn't affected by that bug
