### ISSUE TITLE
miral/configuration_option.h missing

### ISSUE THREAD

**Issue by Leon-Zhang** [Miriway/Miriway#19]
Hello, I get miral/configuration_option.h no such file or directory error when build this source code,
I used sudo apt install libmiral-dev to install miral, and the version is 3.4, is there anything I have missed
which is mandatory to build source code?

**Comment by AlanGriffiths** [comment]
Yes, as described in the README.md

Miriway uses the latest version of Mir available from the mir-team "release" PPA:
```bash
sudo apt-add-repository ppa:mir-team/release
```
