### ISSUE TITLE
Keymap special handling breaks (correct) Miral defaults

### ISSUE THREAD

**Issue by RAOF** [Miriway/Miriway#3]
`miriway`'s [special handling of keymaps](https://github.com/Miriway/Miriway/blob/84f5f7cec879874b3c81b2c27f29253d8c3d3fb7/miriway#L30) overrides Miral's default "extract the keymap from udev properties" behaviour, and (at least on my system), it sets an incorrect keymap.

**Comment by AlanGriffiths** [comment]
On my system, this corrects the default ("us") keymap and uses "gb". @Saviq what's your experience with this?

Looking at the referenced logic, this does seem GNOME specific, so are you using GNOME?

Also, could you provide the keymap you expect and the values from:
```
gsettings get org.gnome.desktop.input-sources current
```
and
```
gsettings get org.gnome.desktop.input-sources sources
```

**Comment by Saviq** [comment]
I didn't need to do anything and my keymap is correct. I did come from a GNOME session, so whatever that set worked.

```plain
$ gsettings get org.gnome.desktop.input-sources current
uint32 0
$ gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'pl')]
```

**Comment by RAOF** [comment]
```
$ gsettings get org.gnome.desktop.input-sources current
uint32 0

$ gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'us+dvorak'), ('xkb', 'au')]
```

Hm. Maybe the script is misparsing the output?

But why is the script trying to parse the output *at all*? This should be readable from the udev properties, and miral does that by default.

**Comment by AlanGriffiths** [comment]
> Maybe the script is misparsing the output?

Well, it _should_ be extracting 'us+dvorak', but `miriway --keymap=us+dvorak` seems to work. However,

```
$ echo "[('xkb', 'us+dvorak'), ('xkb', 'au')]" | grep -Po "'[[:alpha:]]+'\)" | sed -ne "s/['|)]//g;$((1))p"
au
```
So that's the reason it breaks.

> This should be readable from the udev properties, and miral does that by default.

In that case, I'll have to investigate why I get "us" by default.

**Comment by AlanGriffiths** [comment]
...and `grep -Po "'[[:alpha:]+]+'\)"` fixes the parsing

**Comment by AlanGriffiths** [comment]
> In that case, I'll have to investigate why I get "us" by default.

Now I can't reproduce the problem. That makes the fix simpler
