### ISSUE TITLE
Miriway causes hang when it's killed.

### ISSUE THREAD

**Issue by lidgnulinux** [Miriway/Miriway#33]
I'm trying miriway on debian sid, I use Mir palace from ubuntu lunar. It works great, but when I kill it using "killall miriway-shell" or using Ctrl + alt + backspace, my laptop get hung and the fan spins fastly. I even kill the user I used to login but miriway still hang. I dualboot with ubuntu and never face something like that. Any clue ?
Maybe using Mir from ubuntu instead of from debian itself is bad idea ?
Thanks.

**Comment by AlanGriffiths** [comment]
It is not a good idea to mix packages from different distros as there can be strange behaviours. I'd want to rule that out as a cause for this: I'd build and install Mir locally and try to reproduce with that.

**Comment by AlanGriffiths** [comment]
Closing, pending confirmation that this happens without mixing distros
