### ISSUE TITLE
`DISPLAY` selection racing with `shell-component`s

### ISSUE THREAD

**Issue by Saviq** [Miriway/Miriway#5]
#2 worked for me on a slower machine, but now it gets set to empty:

```
$ cat /proc/$( pidof xdg-desktop-portal )/environ | tr '\0' '\n' | grep DISPLAY
DISPLAY=
```
(NB: the portal is DBus-activated)

It looks like `DISPLAY` isn't set yet when `shell-components` are launched.

**Comment by Saviq** [comment]
Another option is to add explicit code in Miriway to set `DISPLAY` through `dbus-update-activation-environment`.

**Comment by AlanGriffiths** [comment]
Ack, `DISPLAY` isn't set until after the Mir server "starts", so the commands would need to be executed via `MirRunner::add_start_callback()`, and not when they are parsed by the `ConfigurationOption` callback (which happens at the end of "init").
