### ISSUE TITLE
Miriway can't find boch-drm_dri.so file

### ISSUE THREAD

**Issue by sergio-costas** [Miriway/Miriway#70]
I'm trying to launch miriway in a Qemu virtual machine, but it shows an error saying that it can't find boch-drm_dri.so file. Where is that library available?

**Comment by AlanGriffiths** [comment]
I can't tell you where that driver is available (I don't see it anywhere in the Ubuntu archive) so I'm guessing it is new and related to virtual displays. That's not really a Miriway issue, but to do with the VM graphics setup.

Miriway ought to work with `virtio-vga,virgl` if that's an option for you

**Comment by sergio-costas** [comment]
Thanks. How can I set it to use any of those? Or better, software rendering (just to make sure that it's not another problem).

**Comment by AlanGriffiths** [comment]
There's a similar scenario described [here](https://discourse.ubuntu.com/t/run-ubuntu-frame-in-a-virtual-machine/29369), obviously you don't want to use an Ubuntu Core image, or Frame, but maybe you can steal from the qemu command line.

You can force software rendering with `export LIBGL_ALWAYS_SOFTWARE=1`

**Comment by sergio-costas** [comment]
Thanks!!!!!
