### ISSUE TITLE
Logind logout does not clean up properly

### ISSUE THREAD

**Issue by Saviq** [Miriway/Miriway#76]
Log in to a Miriway session in GDM, then, in a terminal:

```
$ busctl call \
  org.freedesktop.login1 \
  /org/freedesktop/login1/session/auto 
  org.freedesktop.login1.Session Terminate
```

Expected:
- back to GDM

Current:
- left on splashscreen / text console until Ctrl+Alt+F1

Ctrl+Alt+Backspace works just fine

**Comment by Saviq** [comment]
Just realized GNOME behaves the same, though I'd say that's wrong, still…?

**Comment by AlanGriffiths** [comment]
As Miriway/Mir does nothing to return control to GDM (on VT1) in either case I suspect the problem lies elsewhere.

**Comment by Saviq** [comment]
> As Miriway/Mir does nothing to return control to GDM (on VT1) in either case I suspect the problem lies elsewhere.

Yeah I think something like resources going away before the process gets to shut down properly… still, Miriway was the easiest reproducer, so started here.

**Comment by AlanGriffiths** [comment]
Not sure there is anything here for Miriway
