### ISSUE TITLE
Tap to click support and other protocols support.

### ISSUE THREAD

**Issue by lidgnulinux** [Miriway/Miriway#8]
Hello, it will be nice if `tap to click` support is added, also does miriway support some protocols so panel, and other wayland-related tool work ?

- I try waybar but it's not launch, same for other bar (yambar).
- grimshot screenshot tool not work.
- mate panel is opened at center of the screen, and it's said that the compositor has no layer-shell support.

**Comment by AlanGriffiths** [comment]
Hey, waybar and mate-panel do work. But only if configured as `shell-components` (see the README.md).

I know I need to write some documentation around configuring Miriway, but haven't gotten around to that yet. But one of the features is that some Wayland extensions are not enabled by default for normal applications.

If you're just experimenting to see what work, then you could use `add-wayland-extensions all` (either in the config or as a command-line switch).

**Comment by AlanGriffiths** [comment]
> * grimshot screenshot tool not work.

That's fixed by the latest commit

**Comment by lidgnulinux** [comment]
```
Hey, waybar and mate-panel do work. But only if configured as shell-components (see the README.md).

```
Oh my bad, sorry.

```
If you're just experimenting to see what work, then you could use add-wayland-extensions all (either in the config or as a command-line switch).
```

That's worth a shot, thanks.
